# Generated by Django 3.2.15 on 2022-09-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloglinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=70)),
                ('user_email', models.EmailField(max_length=35)),
                ('user_done', models.BooleanField(default=False)),
            ],
        ),
    ]
