# Generated by Django 3.2.15 on 2023-05-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglinks',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
