# Generated by Django 3.2.15 on 2023-05-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_bloglinks_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglinks',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
